@startuml Register Activity
title Add plant
|User|
start
:Click Create AirPlane button (1);

|System|
:Display 'Create AirPlane screen (2);

|User|
:Enter AirPlane information(3);
:Click Create button (4);

|System|

if(Valid content?(5))then (yes)
:Save Airline(5.1);
:Show create successfully message(6);
:Show AirPlane on "AirPlane manager" screen(7);
stop
else (no)
:Show error message(5.2);
|System|
stop
@enduml