@startuml Register Activity
title Edit Airline
|User|
start
:Click update Airplane (1);

|System|
:Display Airplane detail screen (2);

|User|
:Click Edit button (3);

|System|

:Display 'Edit Airplane' Page(4);
:User update Airplane content(5);
if(Valid content?(6))then (yes)
:Save update Airplane(6.1);
:Show edit successfully message(7);
stop
else (no)
:Show error message(6.2);
|System|
stop
@enduml