@startuml Register Activity
title Create flight
|User|
start
:Click Create Flight button (1);

|System|
:Display 'Create Flight' screen (2);

|User|
:Enter Flight information(3);
:Click Create button (4);

|System|

if(Valid content?(5))then (yes)
:Save Flight(5.1);
:Show create successfully message(6);
:Show Flight on "Flight manager" screen(7);
stop
else (no)
:Show error message(5.2);
|System|
stop
@enduml