@startuml
title Delete flight
|User|
start
:Click delete Airline object(1);
|System|
repeat :Read data(2);
:Display Airline detail screen(3);
|User|
:Click delete button (4);


|System|
:Display delete confirmation screen(5);

|User|
:Confirm deletions of Airline(6);
|System|
repeat while (Yes/ No?) is (no)

:Show delete successfully message(7);

stop
@enduml