@startuml
title Edit Flight
actor User as u
participant Controller as ctrl
participant Service as sv
database Database as db 

u -> ctrl: Flight.show()
activate ctrl
ctrl --> u: editFlightForm.show()
deactivate ctrl
u-> ctrl: Flight.edit()
activate ctrl
ctrl -> ctrl: Validate changing data
alt Input valid
    ctrl -> sv: editFlight(changing info)
    activate sv
    sv -> db: Query to edit Flight (changing info)
    activate db
    db --> sv: return success message
    deactivate db
    sv --> ctrl: return flight
    deactivate sv
    ctrl --> u: Show success message
    ctrl-->u: Show(flightScreen)
else Input invalid
    ctrl --> u: Show error message
    ctrl-->u: Show(flightScreen)
end

@enduml