@startuml
title Search Flight
actor User as u
participant Controller as ctrl
participant Service as sv
database Database as db

u -> ctrl: Request to search Flight (keyword)
activate ctrl
ctrl->sv: Search(keyword)
activate sv
sv->db: Query to show list Flight by Keyword
activate db
db->sv: Return list Flight ()
deactivate db
sv-->ctrl: listFlight()
deactivate sv
ctrl->u:listFlight.show()
deactivate ctrl
@enduml