@startuml
title Delete Voucher 
actor User as u
participant Controller as ctrl
participant Service as sv
database Database as db 

u -> ctrl: Request to delete Voucher (id)
activate ctrl
ctrl->u: Do you want to delete this Voucher? (yes/no)
alt yes
ctrl-> sv:Delete(Voucher.id)
activate sv
sv->db: Query to delete Voucher (id)
activate db
db->sv: return success message
deactivate db
sv-->ctrl: listVoucher
deactivate sv
ctrl-->u: Show success message
ctrl-->u: Show(Voucherscreen)
else no
ctrl-->u: Show(Voucherscreen)
deactivate ctrl
end

@enduml