@startuml
title Search Airport
actor User as u
participant Controller as ctrl
participant Service as sv
database Database as db

u -> ctrl: Request to search Airport (keyword)
activate ctrl
ctrl->sv: Search(keyword)
activate sv
sv->db: Query to show list Airport by Keyword
activate db
db->sv: Return list Airport ()
deactivate db
sv-->ctrl: listAirport()
deactivate sv
ctrl->u:listAirport.show()
deactivate ctrl
@enduml