@startuml Register Activity
title Edit Review
|User|
start
:Click update Review (1);

|System|
:Display Review detail screen (2);

|User|
:Click Edit button (3);

|System|

:Display 'Edit Review' Page(4);
:User update Review content(5);
if(Valid content?(6))then (yes)
:Save update Review(6.1);
:Show edit successfully message(7);
stop
else (no)
:Show error message(6.2);
|System|
stop
@enduml